// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: dial

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H
#include "../ui.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

#ifdef __cplusplus
extern "C"
{
#endif
#include "sdkconfig.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
    typedef enum
    {
        DIAL_PRESS_UP,         // 抬起
        DIAL_PRESS_DOWN,       // 按下
        DIAL_CLICK,            // 单击
        DIAL_DOUBLE_CLICK,     // 双击
        DIAL_LONG_PRESS_START, // 长按开始
        DIAL_LONG_PRESS_UP,    // 长按结束
        DIAL_TURN_RIGHT,       // 右转
        DIAL_TURN_LEFT,        // 左转
        DIAL_RIGH_LIM,         // 右转限位
        DIAL_LEFT_LIM,         // 左转限位
        DIAL_PRESS_RIGHT,      // 按下右转
        DIAL_PRESS_LEFT,       // 按下左转
        DIAL_PRESS_RIGHT_LIM,  // 按下右转限位
        DIAL_PRESS_LEFT_LIM,   // 按下左转限位

        DIAL_SLEEP_TIME, // 休眠事件
        DIAL_SLEEP_WAKE, // 休眠唤醒

        DIAL_WAKENET_DETECTED,//识别到唤醒词
        DIAL_WAKENET_NO_DETECT,

    } dial_event_t;

    void dial_event_init();

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
